### PR TITLE
Add pkgbuild stuff

### PR DESCRIPTION
**Pull request by tkit1994**
Add pkgbuild stuff and update readme.

### CODE REVIEW

**Comment by cra0zy** [comment]
To not add to many notes, can you remove the README changes, I'll update it.

**Comment by cra0zy** [comment]
On a note of dependencies, should we add vs code as optional dep?

(I say optional as there are multiple variants of it on Arch repos / AUR)

**Comment by tkit1994** [comment]
l've remove the README changes, and add vscode to optdepends by add the following line to PKGBUILD.

```bash
optdepends=('code: The Visual Studio Code (vscode) editor')
```

**Comment by cra0zy** [comment]
Thnaks @tkit1994 for this, looks great, merging!

**Pull request merged**
